"""carchartcomments

Revision ID: 31575c1c6e36
Revises: cca50a085332
Create Date: 2023-12-21 22:26:58.058287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31575c1c6e36'
down_revision = 'cca50a085332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_chart_user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('car_chart_user_id')

    # ### end Alembic commands ###
