"""Initial migration

Revision ID: 45a9efe3910f
Revises: 
Create Date: 2023-10-18 10:22:42.073398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a9efe3910f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_data', schema=None) as batch_op:
        batch_op.drop_constraint('unique_model_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_model_id', ['model_id'])

    # ### end Alembic commands ###
