"""wiki carimage columns

Revision ID: 4693e2eaa2df
Revises: 31575c1c6e36
Create Date: 2023-12-28 15:11:10.106633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4693e2eaa2df'
down_revision = '31575c1c6e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attribution', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_images', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('attribution')

    # ### end Alembic commands ###
