"""Added event relationships w foreignkey

Revision ID: 880ccf83073d
Revises: d0ad3a54308d
Create Date: 2023-11-24 19:58:30.012019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880ccf83073d'
down_revision = 'd0ad3a54308d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('association_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['association_id'], ['user_car_association.id'], ),
    sa.ForeignKeyConstraint(['car_id'], ['car_data.model_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
