"""Initial migration

Revision ID: b6f24e3931ad
Revises: 
Create Date: 2023-10-25 18:21:15.454203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f24e3931ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_data',
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('model_make_id', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('model_trim', sa.Text(), nullable=True),
    sa.Column('model_year', sa.BigInteger(), nullable=True),
    sa.Column('model_body', sa.Text(), nullable=True),
    sa.Column('model_engine_position', sa.Text(), nullable=True),
    sa.Column('model_engine_cc', sa.BigInteger(), nullable=True),
    sa.Column('model_engine_cyl', sa.Float(), nullable=True),
    sa.Column('model_engine_type', sa.Text(), nullable=True),
    sa.Column('model_engine_valves_per_cyl', sa.Float(), nullable=True),
    sa.Column('model_engine_power_ps', sa.Float(), nullable=True),
    sa.Column('model_engine_power_rpm', sa.Float(), nullable=True),
    sa.Column('model_engine_torque_nm', sa.Float(), nullable=True),
    sa.Column('model_engine_torque_rpm', sa.Float(), nullable=True),
    sa.Column('model_engine_bore_mm', sa.Float(), nullable=True),
    sa.Column('model_engine_stroke_mm', sa.Float(), nullable=True),
    sa.Column('model_engine_compression', sa.Text(), nullable=True),
    sa.Column('model_engine_fuel', sa.Text(), nullable=True),
    sa.Column('model_top_speed_kph', sa.Float(), nullable=True),
    sa.Column('model_0_to_100_kph', sa.Float(), nullable=True),
    sa.Column('model_drive', sa.Text(), nullable=True),
    sa.Column('model_transmission_type', sa.Text(), nullable=True),
    sa.Column('model_seats', sa.Float(), nullable=True),
    sa.Column('model_doors', sa.Float(), nullable=True),
    sa.Column('model_weight_kg', sa.Float(), nullable=True),
    sa.Column('model_length_mm', sa.Float(), nullable=True),
    sa.Column('model_width_mm', sa.Float(), nullable=True),
    sa.Column('model_height_mm', sa.Float(), nullable=True),
    sa.Column('model_wheelbase_mm', sa.Float(), nullable=True),
    sa.Column('model_lkm_hwy', sa.Float(), nullable=True),
    sa.Column('model_lkm_mixed', sa.Float(), nullable=True),
    sa.Column('model_lkm_city', sa.Float(), nullable=True),
    sa.Column('model_fuel_cap_l', sa.Float(), nullable=True),
    sa.Column('model_sold_in_us', sa.BigInteger(), nullable=True),
    sa.Column('model_co2', sa.Float(), nullable=True),
    sa.Column('model_make_display', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=50), nullable=True),
    sa.Column('is_google_account', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_car_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.BigInteger(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('memories', sa.Text(), nullable=True),
    sa.Column('year_purchased', sa.Integer(), nullable=True),
    sa.Column('has_custom_image', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['car_data.model_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['association_id'], ['user_car_association.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_images')
    op.drop_table('user_car_association')
    op.drop_table('users')
    op.drop_table('car_data')
    # ### end Alembic commands ###
