"""Add custom car make model variant

Revision ID: d0ad3a54308d
Revises: ea22964ac43f
Create Date: 2023-11-07 17:26:18.083264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ad3a54308d'
down_revision = 'ea22964ac43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_car_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_custom', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('custom_make', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('custom_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('custom_variant', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_car_association', schema=None) as batch_op:
        batch_op.drop_column('custom_variant')
        batch_op.drop_column('custom_model')
        batch_op.drop_column('custom_make')
        batch_op.drop_column('is_custom')

    # ### end Alembic commands ###
