"""initial migration

Revision ID: e207e2813c1c
Revises: 
Create Date: 2023-10-17 22:16:46.150304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e207e2813c1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    with op.batch_alter_table('car_data', schema=None) as batch_op:
        batch_op.alter_column('model_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_constraint('unique_model_id', type_='unique')

    with op.batch_alter_table('car_images', schema=None) as batch_op:
        batch_op.alter_column('association_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('web_image_url')
        batch_op.drop_column('attribution_text')

    with op.batch_alter_table('general_car_images', schema=None) as batch_op:
        batch_op.alter_column('model_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('user_car_association', schema=None) as batch_op:
        batch_op.drop_constraint('user_car_association_user_id_model_id_key', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_email_key', ['email'])

    with op.batch_alter_table('user_car_association', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_car_association_user_id_model_id_key', ['user_id', 'model_id'])

    with op.batch_alter_table('general_car_images', schema=None) as batch_op:
        batch_op.alter_column('model_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('car_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attribution_text', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('web_image_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('association_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('car_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_model_id', ['model_id'])
        batch_op.alter_column('model_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    op.create_table('car',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='car_pkey')
    )
    # ### end Alembic commands ###
