"""New sharing migration

Revision ID: e85812ae0494
Revises: 5362e290e126
Create Date: 2023-11-27 20:13:18.147179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e85812ae0494'
down_revision = '5362e290e126'
branch_labels = None
depends_on = None


def upgrade():
    # Manually create the ENUM type
    sharing_preference_enum = postgresql.ENUM('Global', 'Sharing', 'Private', name='sharing_preference_enum', create_type=False)
    sharing_preference_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sharing_preference', sharing_preference_enum, nullable=True))
        batch_op.drop_column('happy2show')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('happy2show', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('sharing_preference')

    # ### end Alembic commands ###
