from app import db

class Car(db.Model):
    __tablename__ = 'car_data'
    
    model_id = db.Column(db.BigInteger, primary_key=True)
    model_make_id = db.Column(db.Text)
    model_name = db.Column(db.Text)
    model_trim = db.Column(db.Text)
    model_year = db.Column(db.BigInteger)
    model_body = db.Column(db.Text)
    model_engine_position = db.Column(db.Text)
    model_engine_cc = db.Column(db.BigInteger)
    model_engine_cyl = db.Column(db.Float)
    model_engine_type = db.Column(db.Text)
    model_engine_valves_per_cyl = db.Column(db.Float)
    model_engine_power_ps = db.Column(db.Float)
    model_engine_power_rpm = db.Column(db.Float)
    model_engine_torque_nm = db.Column(db.Float)
    model_engine_torque_rpm = db.Column(db.Float)
    model_engine_bore_mm = db.Column(db.Float)
    model_engine_stroke_mm = db.Column(db.Float)
    model_engine_compression = db.Column(db.Text)
    model_engine_fuel = db.Column(db.Text)
    model_top_speed_kph = db.Column(db.Float)
    model_0_to_100_kph = db.Column(db.Float)
    model_drive = db.Column(db.Text)
    model_transmission_type = db.Column(db.Text)
    model_seats = db.Column(db.Float)
    model_doors = db.Column(db.Float)
    model_weight_kg = db.Column(db.Float)
    model_length_mm = db.Column(db.Float)
    model_width_mm = db.Column(db.Float)
    model_height_mm = db.Column(db.Float)
    model_wheelbase_mm = db.Column(db.Float)
    model_lkm_hwy = db.Column(db.Float)
    model_lkm_mixed = db.Column(db.Float)
    model_lkm_city = db.Column(db.Float)
    model_fuel_cap_l = db.Column(db.Float)
    model_sold_in_us = db.Column(db.BigInteger)
    model_co2 = db.Column(db.Float)
    model_make_display = db.Column(db.Text)
    users = db.relationship("UserCarAssociation", back_populates="car")
 